### ISSUE TITLE
Create a new logo for the project

### ISSUE THREAD

**Issue by Toughee** [Toughee/LiteReport#5]
# Type of Issue:

* New feature request

# Recent issue description

![litereport-icon](https://user-images.githubusercontent.com/21093554/66694559-45a33580-ec7a-11e9-8d9c-311145f2360c.png)

Current image could use some improvements. Something that incorporates what this project is about in a single, iconic image. 

# Possible solution:

A new set of images for the project in different dimensions (292x292, favicon size, etc)

# Your current work environment:
Tools used, what platform was this PR made in, OS version and number

**Comment by tmoran18** [comment]
Hi,

I would like to have a go at this, I could create something similar to these but with some more colour in them and the LiteReport name underneath?

![lighthouse2](https://user-images.githubusercontent.com/39853480/66695893-fdcbef00-ed09-11e9-91b6-c17746fcd4f3.JPG)
![lighthouse1](https://user-images.githubusercontent.com/39853480/66695896-06bcc080-ed0a-11e9-86fb-ab3da0ce3ea6.JPG)

**Comment by Toughee** [comment]
Hello @tmoran18 

Thank you for submitting your artwork. I really liked the first image you submitted. Maybe try incorporating a folder along the image. Basically, all reports would go to a specific folder, so I also wanted to have that inside the image

Let me know if this is something you can do. I will be sure to add you to the list of contributors as soon as everything has been done.

**Comment by tmoran18** [comment]
What about something like this? Do You want the LiteReport title text underneath?
![liteReport](https://user-images.githubusercontent.com/39853480/66709766-3de4ad80-edae-11e9-9ac5-a21f8e88aaad.png)

**Comment by Toughee** [comment]
@tmoran18  Yes, this looks good. Maybe not have any seagulls inside the folder. Adding the first image  you created in the folder would look good too. Let me know if you can do this.

**Comment by Toughee** [comment]
@tmoran18  Hello
Just wanted to do a status check to see how everything is going in regards to this issue

**Comment by tmoran18** [comment]
Hi I submitted another pr with the new logo you wanted. Is it not showing
up correctly?

**Comment by Toughee** [comment]
@tmoran18 How odd. It only showed up for me right now. Okay, I'll look at this tomorrow. Thank you for the help

**Comment by Toughee** [comment]
Hello @tmoran18. I looked at your recent PR. Everything looks good. Great job! I will add you to the list of contributors inside this project in my next PR to the master.
